#!/bin/bash 
RED='\033[0:31m'
NC='\033[0m'  # No Color

err=$(npm run dev | grep -e error -e failing)

if [ ${#err} -gt 0 ]; then
    echo -e "${RED}Your commit failed, run test and lint on your code${NC}"
    exit 1
fi
